const authRoutes = require("./auth.routes");
const userRoutes = require("./user.routes");
const uploadRouter = require("./upload.routes");
const categoryRoutes = require("./category.routes");
const eventRoute = require("./event.routes");
const payoutMethodRoute = require("./payout.routes");
const orderRoute = require("./order.routes");
const paymentRoute = require("./payment.routes");
const webhookRoutes = require("./webhook.routes");
const orderItemRoutes = require("./orderItem.routes");
const ticketRoutes = require("./ticket.routes");
const transactionRoutes = require("./transaction.routes");
const staffPermissionRoutes = require("./staffPermission.routes");
const nftRoutes = require("./nft.routes");
const homeRoutes = require("./home.routes");
const dashboardRoutes = require("./dashboard.routes");
const adminUserRoutes = require("./adminUser.routes");
const adminEventRoutes = require("./adminEvent.routes");
const reportRoutes = require("./report.routes");
const adminTransactionRoutes = require("./adminTransaction.routes");
const checkinRoutes = require("./checkin.routes");

const initRoutes = (app) => {
  app.use("/api/auth", authRoutes);
  app.use("/api/user", userRoutes);
  app.use("/api/uploads", uploadRouter);
  app.use("/api/categories", categoryRoutes);
  app.use("/api/events", eventRoute);
  app.use("/api/payout-methods", payoutMethodRoute);
  app.use("/api/orders", orderRoute);
  app.use("/api/payment", paymentRoute);
  app.use("/api/webhooks", webhookRoutes);
  app.use("/api/order-items", orderItemRoutes);
  app.use("/api/tickets", ticketRoutes);
  app.use("/api/transactions", transactionRoutes);
  app.use("/api/staff-permissions", staffPermissionRoutes);
  app.use("/api/nft", nftRoutes);
  app.use("/api/home", homeRoutes);
  app.use("/api/admin/dashboard", dashboardRoutes);
  app.use("/api/admin/users", adminUserRoutes);
  app.use("/api/admin/events", adminEventRoutes);
  app.use("/api/admin/reports", reportRoutes);
  app.use("/api/admin/transactions", adminTransactionRoutes);
  app.use("/api/check-in", checkinRoutes);
};
module.exports = initRoutes;
